### PR TITLE
[ISSUE #10] add react module for dashboard

### PR DESCRIPTION
**Pull request by RaymondCode**
## What is the purpose of the change

https://github.com/apache/rocketmq-dashboard/issues/10

Separate the front-end and back-end modules and add react demo.

You can build it by cmd below
```
mvn clean package -Dmaven.test.skip=true
java -jar target/rocketmq-dashboard-2.0.0.jar
```
or just 
```
 mvn spring-boot:run
```
Then you can visit /app.html for previewing

## Brief changelog

1. Add /frontend dir and add react code in it
2. Add maven plugin for packaging all resource in one jar

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by StyleTang — APPROVED** [review]
Thanks for your creative work, the front-end modules can now be compiled and packaged into spring-boot server.👍 With this feature, we can continue to optimize our front-end framework and migrate old page to it.

image

**Comment by vongosling** [comment]
If I remember correctly, ASF lists the reactor license as ALv2 incompatible. So look carefully at the documentation and look for a replacement.

**Comment by StyleTang** [comment]
> If I remember correctly, ASF lists the reactor license as ALv2 incompatible. So look carefully at the documentation and look for a replacement.

Before September 2017, React used the BSD License, we should not include it.
But after this [commit](https://github.com/facebook/react/commit/b765fb25ebc6e53bb8de2496d2828d9d01c2774b#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) react license was changed to MIT.

According to [Apache CATEGORY A: WHAT CAN WE INCLUDE IN AN ASF PROJECT?](https://www.apache.org/legal/resolved.html#category-a), it is available, do we have other concerns about React?

**Comment by vongosling** [comment]
> > If I remember correctly, ASF lists the reactor license as ALv2 incompatible. So look carefully at the documentation and look for a replacement.
> 
> Before September 2017, React used the BSD License, we should not include it.
> But after this [commit](https://github.com/facebook/react/commit/b765fb25ebc6e53bb8de2496d2828d9d01c2774b#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) react license was changed to MIT.
> 
> According to [Apache CATEGORY A: WHAT CAN WE INCLUDE IN AN ASF PROJECT?](https://www.apache.org/legal/resolved.html#category-a), it is available, do we have other concerns about React?

Great, we should care for  Facebook BSD+Patents license in X category, which is the React prior license. Do we have any optional for here. I still have some concerns about this happening over and over again.

**Comment by StyleTang** [comment]
> Great, we should care for Facebook BSD+Patents license in X category, which is the React prior license. Do we have any optional for here. I still have some concerns about this happening over and over again.

If we want to use React, maybe we can use the current version of React because it uses the MIT license. Once the license is changed we should not upgrade the React version.

React Vue Angular are the most popular front end frameworks, most front end users choose React, I prefer to use it, we can discuss which front end framework to use in this [issue](https://github.com/apache/rocketmq-dashboard/issues/11).

This PR is a solution for building front end resources into spring jar(choose to use node/npm and maven plugin), React is not a must.

**Comment by vongosling** [comment]
> > Great, we should care for Facebook BSD+Patents license in X category, which is the React prior license. Do we have any optional for here. I still have some concerns about this happening over and over again.
> 
> If we want to use React, maybe we can use the current version of React because it uses the MIT license. Once the license is changed we should not upgrade the React version.
> 
> React Vue Angular are the most popular front end frameworks, most front end users choose React, I prefer to use it, we can discuss which front end framework to use in this [issue](https://github.com/apache/rocketmq-dashboard/issues/11).
> 
> This PR is a solution for building front end resources into spring jar(choose to use node/npm and maven plugin), React is not a must.

Up, If there's nothing wrong with the agreement, I'm in favor of the react, which is an active and creative community project.

**Comment by RaymondCode** [comment]
I have resolved the conflict, please review it again, thanks.

**Pull request merged**
